### ISSUE TITLE
Crashes at start

### ISSUE THREAD

**Issue by elpaso** [tiagoshibata/Android-GPSd-Client#1]
- Install
- Enter IP and port
- Hit Start
- crash

**Comment by tiagoshibata** [comment]
Thanks for the report. Do you have logcat output? What's the phone model and Android version?

**Comment by elpaso** [comment]
Sorry, I don't have any log, phone is a motorola G3

**Comment by tiagoshibata** [comment]
Can you collect logcat logs and specify the Android version, please?

**Comment by elpaso** [comment]
I'm not an android developer but if you explain me how to collect the logs I will try (`adb` is installed and the phone is in developer mode)

Android is 6.0.1

**Comment by tiagoshibata** [comment]
Okay, with developer mode enabled and `adb` installed, running `adb logcat` should show you the logs in your terminal. The following should be enough to start with (with comments added for clarity):

```
# Open your home screen in your phone
# In a computer connected to your phone and with developer access, type the following:
adb logcat -c  # clear logcat history
adb logcat > crash.log  # save logs to crash.log in the curret directory
# Run GPSd Client in your phone now
# After the crash, interrupt 'adb logcat' and upload crash.log to this issue.
```

Thanks for the support!

**Comment by csongor666** [comment]
Same issue with Android 6.0, Zopo Speed 8 device. Server address: 10.0.0.1 port: 8089, reachable
See the log below:
[crash.log](https://github.com/tiagoshibata/Android-GPSd-Client/files/1841650/crash.log)
Please find out how to make it work. Should be nice to send GPS data from my mobile to Raspberry PI.
THX

**Comment by tiagoshibata** [comment]
Thank you, I'll look into it. I see that it's crashing when loading the notification icon:

```
--------- beginning of crash
03-23 14:32:47.663  2100  2100 E AndroidRuntime: FATAL EXCEPTION: main
03-23 14:32:47.663  2100  2100 E AndroidRuntime: Process: io.github.tiagoshibata.gpsdclient, PID: 2100
03-23 14:32:47.663  2100  2100 E AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package io.github.tiagoshibata.gpsdclient: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=io.github.tiagoshibata.gpsdclient id=0x7f020002) visible user=0 )
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5683)
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-23 14:32:47.663  2100  2100 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

I tested on my two devices and couldn't reproduce. Googling around shows that some devices have problems with vector icons, I'll see if using images fixes the problem.

**Comment by tiagoshibata** [comment]
I'm not sure if using a PNG instead of a vector file will fix this issue, but I'll release an update later today.

Edit: Pushed to beta testing and running tests, will promote to production if everything is fine. You can test it yourself if you have beta testing enrollment in the Play Store.

**Comment by tiagoshibata** [comment]
@csongor666 @elpaso Let me know if the latest release on the Play Store works for you, the bug seems fixed.

**Comment by csongor666** [comment]
It works perfect! :)
THX
