### ISSUE TITLE
Run as Autostart

### ISSUE THREAD

**Issue by carlonjohn** [tiagoshibata/Android-GPSd-Client#13]
Any thoughts about the possibility to configure it to run automatically and start streaming to a configured address on phone startup?

Thanks

**Comment by tiagoshibata** [comment]
Yes, could be done. If it's something you're interested in coding I would accept a PR, or I can work on it.

**Comment by tiagoshibata** [comment]
Let me know if you're still interested in the feature, else I'll close the issue.

**Comment by carlonjohn** [comment]
Sorry.  The message got lost in my mail.  I think I’ve figured out another way to go, but thanks.
