### ISSUE TITLE
Feature request - GPS timer in milliseconds

### ISSUE THREAD

**Issue by julianoborba** [tiagoshibata/Android-GPSd-Client#20]
@tiagoshibata , thank you for that app. It works very well.

I'm in no position to ask for new features to you. But, please, at least let me express a request.

It would be possible to implement a timer function? Where given a input in milliseconds, the application adjust the interval of how often it receive data from GPS. For example, if said interval is set to 4000, GPSd should receive NMEA strings each 4 seconds.

The motivation for that request is just to enable a way to adjust GPS polling for a slow paced walking device. Think of a walking person who takes 4-6 seconds to get a significant location movement to be polled - I'm currently using your application for warwalking, and take control of said interval can be invaluable.

Best regards.

**Comment by tiagoshibata** [comment]
Hi @julianoborba,

Sorry, I haven't been active on GitHub. This application forwards all NMEA messages directly. If you need some throttling logic, it could be implemented on the client.
