### ISSUE TITLE
resources.arsc is a malware of type Android.Trojan.Neucore.gTVTY

### ISSUE THREAD

**Issue by FathiBenNasr** [tiagoshibata/Android-GPSd-Client#4]
Hello,
I have Bitdefender antivirus installed on my smartphone, which alerted me that GPSd-Client is a malware. Si, I opened a ticket with my antivirus support for this and they required me to send them the apk. When trying to download it on my computer, I receive the following message: "On-access scanning has detected a threat. The file has been removed.C: \ Users \... \ Temp \ PBbyfq4e.apk.part => resources.arsc is a malware of type Android.Trojan.Neucore.gTVTY".

Could you please confirm that this is a false alert and that the apk doen't contain any malware ?
TIA

**Comment by tiagoshibata** [comment]
Hi,

Where did you download it from? The Play Store? These APKs were built by me; I believe your antivirus is giving you a false positive.

Do you have more details about the detected malware? I ran resources.arsc on VirusTotal and it found nothing: https://www.virustotal.com/#/file/1a2e1ba98679312b1c8c031a02436ccaea01b5ff3cc7eb793219b5b856f662d9/detection

**Comment by tiagoshibata** [comment]
Closing, I'll reopen if more information is provided.

**Comment by FathiBenNasr** [comment]
I have also opened a ticket with the antivirus support team and after rechecking they finally removed GPSd-Client from their malware list. It is no more detected as a malware.
