### ISSUE TITLE
[feature request] remember the last typed values

### ISSUE THREAD

**Issue by BrainDamage** [tiagoshibata/Android-GPSd-Client#5]
It'd be nice if the app would remember the last typed values for address and port of the gpsd daemon, they are unlikely to change and it'd save typing every time the app is launched again

**Comment by tiagoshibata** [comment]
It already does ([code](https://github.com/tiagoshibata/Android-GPSd-Client/blob/48a0f384a2d776fd93837b9d7724a60b9725fbb5/app/src/main/java/io/github/tiagoshibata/gpsdclient/MainActivity.java#L65-L97)). Is it not working for you? How are you closing the app?

**Comment by BrainDamage** [comment]
I think the reason why it failed to save was because the two times I've used it my phone ran out of battery from extra drain of streaming the gps. I have manually launched and closed it and it is saved now.
