### ISSUE TITLE
gpsd:WARN: Overlong packet of 105 chars rejected.

### ISSUE THREAD

**Issue by Aajnow** [tiagoshibata/Android-GPSd-Client#6]
I am getting this error when i start gpsd and the latitude and longitude are not logged.
Any pointers ?

**Comment by tiagoshibata** [comment]
Hmm, I've never seen this error. It seems like your device is giving us very long NMEA packets. Can you post the packets here? If you have netcat installed, `nc -lup <port number>` or `nc -lu <port number>` could print the packets to the terminal depending on your netcat version (if it doesn't look up the manual with `man netcat`, or use `socat`: `socat UDP-RECV:5555 STDOUT`)

**Comment by tiagoshibata** [comment]
Rationale from gpsd's source code:

```c
/*
 * We've had reports that on the Garmin GPS-10 the device sometimes
 * (1:1000 or so) sends garbage packets that have a valid checksum
 * but are like 2 successive NMEA packets merged together in one
 * with some fields lost.  Usually these are much longer than the
 * legal limit for NMEA, so we can cope by just tossing out overlong
 * packets.  This may be a generic bug of all Garmin chipsets.
 */
if (strlen(sentence) > NMEA_MAX) {
    gpsd_report(LOG_WARN, "Overlong packet of %zd chars rejected.\n",
	            strlen(sentence));
    return ONLINE_SET;
}
```

Your device is probably sending invalid NMEA packets to your applications. I can see if we can work around it if you post the raw packets.

**Comment by Aajnow** [comment]
okay, so when the gpsclient (andriod phone)is not able to lock on a latitude and longitude when its under a roof with no clear sky access it was throwing this error. As soon as I went under the clear sky all worked well.
Thanks!

**Comment by tiagoshibata** [comment]
Good to know. Currently the app forwards NMEA packets from the GPS as-is, I'll probably add some validation (maximum length, delimiters and checksum) in the next version and show a warning if they fail.
