### ISSUE TITLE
Application name is misleading -- not a gpsd client.

### ISSUE THREAD

**Issue by lbdroid** [tiagoshibata/Android-GPSd-Client#7]
A gpsd client is something that connects to a gpsd server in order to RECEIVE/CONSUME location data. In the case of Android, that would imply a HAL, which would allow Android to become a client of gpsd. This is a feeder application, not a gpsd client. Strictly speaking, gpsd becomes a CLIENT of THIS.

Gpsd now includes an Android HAL, as well as a demo client written in C.

**Comment by tiagoshibata** [comment]
I'm willing to change the name if you have a good alternative. GPSd feeder? GPSd forwarder? I'll give it some thought too.

**Comment by lbdroid** [comment]
feeder, forwarder, backend, anything of that sort would be suitable.

**Comment by tiagoshibata** [comment]
I'm changing the name to GPSd Forwarder next time I do a release.
