### ISSUE TITLE
On Issue with Android 10?

### ISSUE THREAD

**Issue by tpacri** [tiagoshibata/Android-GPSd-Client#8]
I have a Pixel3A and afterupdating to Android10, it stopped working. Application runs fine and shows same output but data never reaches the destination

**Comment by tiagoshibata** [comment]
I'll update my phone to Android 10 and give it a try. Thanks for reporting!

**Comment by tiagoshibata** [comment]
I've been busy with life things (moved countries and am getting settled in) and didn't have time to fix this. I didn't forget about it, I'll take a closer look once I get a development machine ready. Thanks for the patience.

**Comment by tiagoshibata** [comment]
Got a fix! Will test on older Android versions and make sure it's working properly tonight.

**Comment by tiagoshibata** [comment]
I'm publishing the fix, let me know if you have further problems.
